### ISSUE TITLE
Unable to see Stop button in 1366 x 768 screen resolution

### ISSUE THREAD

**Issue by gojimmypi** [jamesbowman/i2cdriver#11]
perhaps the radio buttons can be vertically pushed closer together a bit, or add a scrollbar for those that have lower resolution screens? I would have submitted PR for this, but could not find the GUI version source code.

**Comment by jamesbowman** [comment]
Aha, this is on Windows.
Sure, there are a couple of changes I can make.
btw the source is at ``python/samples/i2cgui.py``

**Comment by jamesbowman** [comment]
Yes, pushing the radio buttons closer together looks good. Now fits in 768:

![image](https://user-images.githubusercontent.com/894763/54079170-6d698f80-428c-11e9-9245-1986d541052c.png)

**Comment by gojimmypi** [comment]
yes, that works perfectly! (and looks better, too -  in addition to being able to see the Stop button) 

thank you for the prompt response & I didn't realize Windows GUI was python based.
