### ISSUE TITLE
bitbang?

### ISSUE THREAD

**Issue by williamkapke** [jamesbowman/i2cdriver#20]
While creating a [Node.js module](https://www.npmjs.com/package/i2cdriver) for this device- I came across bitbang mode (commands `b` & `i`)... but [I couldn't find any further details on it](https://github.com/jamesbowman/i2cdriver/search?q=bitbang&unscoped_q=bitbang).

Can you share insights on how this works? Maybe it's still in development?

**Comment by jamesbowman** [comment]
Pushed new PDF to public site.
Closing.
