### ISSUE TITLE
Seems to hang ?

### ISSUE THREAD

**Issue by lakidd** [jamesbowman/i2cdriver#3]
Hi I've just received my i2cdriver.
I plug it in and it lights up with the default screen, but it doesn't 'do' anything. When running i2ccl with the correct device name, it just seems to hang, i don't get the status line like your example.
Any hints on troubleshooting ?
Sorry this is on OSX. The python gui also seems to have issues with 
```
TypeError: GridSizer(): arguments did not match any overloaded call:
  overload 1: not enough arguments
  overload 2: argument 2 has unexpected type 'int'
  overload 3: not enough arguments
  overload 4: not enough arguments


```
And from my reading, it does need 3x parameters in the call.
Thanks

**Comment by jamesbowman** [comment]
What device name are you using? Something like:

``/dev/cu.usbserial-XXXXXXXX``

?

**Comment by lakidd** [comment]
Aha its /dev/tty.usbserial-WEATHER...when i change to the cu.usbserial-WEATHER, it comes good, thanks.
What is the difference between those nodes ? I've never understood why both appear and for all other arduino, esp stuff the tty nodes work fine.
Any thoughts on the python issue ?

**Comment by jamesbowman** [comment]
Yes it is subtle, but this explains tty vs cu in more detail.

https://pbxbook.com/other/mac-tty.html

Please can you raise a new issue for the Python GUI? (WX changed the parameters of GridSizer between versions.)

**Comment by jamesbowman** [comment]
OK, think this is closed.
