### ISSUE TITLE
Clock stretching?

### ISSUE THREAD

**Issue by jessica-mulein** [jamesbowman/i2cdriver#38]
Can you tell me about anything I need to do specifically to handle clock stretching? What is supported? I'm switching from the Raspberry Pi's internal I2c circuit to yours hoping to avoid issues with that- but will I? the RPI supports clock stretching during ACK but i keep getting the famous i2c lockouts.

**Comment by jamesbowman** [comment]
Apologies, I missed this. Clock stretching is fully supported by the I2CDriver, and is always enabled.  There's nothing to enable.
