### ISSUE TITLE
Python GUI crashes

### ISSUE THREAD

**Issue by lakidd** [jamesbowman/i2cdriver#4]
When running the python gui I get 

`Traceback (most recent call last):
  File "./i2cgui.py", line 215, in <module>
    f = Frame()
  File "./i2cgui.py", line 99, in __init__
    devgrid = wx.GridSizer(14, 8)
TypeError: GridSizer(): arguments did not match any overloaded call:
  overload 1: not enough arguments
  overload 2: argument 2 has unexpected type 'int'
  overload 3: not enough arguments
  overload 4: not enough arguments`

Has GridSizer in wxPython changed ?

**Comment by jamesbowman** [comment]
Confirmed fixed on wx. Closing.
