### ISSUE TITLE
Does not run on Windows 10 x64

### ISSUE THREAD

**Issue by Kabron287** [jamesbowman/i2cdriver#41]
6 releases and it does not work!
Windows 10 x64 LTSC. Two processes in Task manager do nothing.
Cmpatibility/Admin Rights not help.

CLI not better
![2020-03-07_174632](https://user-images.githubusercontent.com/2493191/76145602-cfc1bf80-609b-11ea-820e-3b5b1939510f.jpg)

**Comment by jamesbowman** [comment]
When you say "two processes in Task manager" are these old I2CDriver GUI processes?

Maybe kill them or reboot, and try running the GUI again?

**Comment by Kabron287** [comment]
Each launch creates two processes. The second one waits for the first.
![Wait](https://user-images.githubusercontent.com/2493191/76159030-64c0c900-612d-11ea-9af5-60d089143229.jpg)
