### ISSUE TITLE
Bus arbitration

### ISSUE THREAD

**Issue by limi97** [jamesbowman/i2cdriver#54]
Can you tell me about anything I need to do specifically to handle bus arbitration? What is supported? If I do the start command the arbitration bit is always set. How can I change this?

**Comment by jamesbowman** [comment]
![image](https://user-images.githubusercontent.com/894763/95996951-1b81d780-0de8-11eb-8dbb-e3ceec37fbf7.png)

This bit should definitely be zero. Being set suggests that either SCL or SDA is tied low. As a first test, I suggest you:

1. remove power from I2CDriver
2. remove all I2C peripherals from I2CDriver
3. apply power to I2CDriver

And check if the **start** still leaves ARB high. If it does, the I2CDriver has a hardware fault, and I can replace it. If not, there is a problem with the I2C peripheral not releasing the bus.

**Comment by limi97** [comment]
I tested this. The bit is zero if there is no peripheral connected to the driver. But if I connect a peripheral the bit goes one. I connected several options.

**Comment by jamesbowman** [comment]
Aha, thanks. On the software side, are you using the C library, Python, or something else?

**Comment by jamesbowman** [comment]
Also (sorry to have to ask this, but it has happened before) have you checked your hookup that SDA and SCL re not swapped? SCL is yellow, SDA is blue.

**Comment by limi97** [comment]
Yes I have it the right way. Actually now it works. I did again what you described and now it works perfectly fine.

**Comment by limi97** [comment]
Thanks for your help
