### ISSUE TITLE
i2cgui is not functional code.

### ISSUE THREAD

**Issue by rhyde** [jamesbowman/i2cdriver#6]
I have fixed a couple obvious problems but I quickly realized that this is at best a stub and very little works.  When will a tool that was advertised be available?
Issues: Wrong number of arguments creating the grid layout.
Can't handle non i2c usb-serial devices.

Randomly will not connect claiming bus is busy

**Comment by jamesbowman** [comment]
Good points... this in progress.

When it says the bus is busy, what does the ``i2ccl <port> i`` report?

**Comment by rhyde** [comment]
The client tool is responding as expected.

**Comment by jamesbowman** [comment]
Hmm, and ``i2ccl <port> d`` produces a reasonable port scan?

**Comment by jamesbowman** [comment]
Think it is feature complete now. Tested on Mac, seems to be usable.
Raised #7 to cover the work to expose the programmable pull-ups.

**Comment by jamesbowman** [comment]
![image](https://user-images.githubusercontent.com/894763/53703899-b53f7100-3dcb-11e9-9459-16646d464d3e.png)
