### ISSUE TITLE
Where is protocol.md?

### ISSUE THREAD

**Issue by njh** [jamesbowman/i2cdriver#8]
Hi,

Just read about this project on an email from Cool Components - looks great!

I just clicked on 'The serial protocol is **very simple**, and there are included drivers for' and got a 404. Where can I find out about the protocol?

Thanks,

nick.

**Comment by jamesbowman** [comment]
Fixed the old text, copy-pasted from SPIDriver.
The protocol is covered here

https://i2cdriver.com/#raw-protocol

**Comment by njh** [comment]
Ah, great, thanks.

It might be good to add a link to https://i2cdriver.com/ in the header of the Github repo.

**Comment by jamesbowman** [comment]
Good idea - done.
